function S($s){[regex]::Unescape($s)}
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$ErrorActionPreference="Stop"
$root=(Resolve-Path (Join-Path $PSScriptRoot "..")).Path;$app="YouTube AI Agent"
function NodePath {$c=Get-Command node.exe -ErrorAction SilentlyContinue;if($c){return $c.Source};foreach($p in @("$env:ProgramFiles\nodejs\node.exe","$env:LOCALAPPDATA\Programs\nodejs\node.exe")){if(Test-Path $p){return $p}}}
function EnsureNode {$n=NodePath;if($n -and [int]((& $n --version).TrimStart("v").Split(".")[0])-ge 18){return $n};$w=Get-Command winget.exe -ErrorAction SilentlyContinue;if(-not$w){throw "Node.js 18+ və winget tələb olunur."};if([System.Windows.Forms.MessageBox]::Show("Node.js 18+ tapılmadı. LTS quraşdırılsın?",$app,"YesNo","Question")-ne"Yes"){throw "Node.js quraşdırılmadı."};Start-Process $w.Source -ArgumentList "install --id OpenJS.NodeJS.LTS -e --source winget --accept-source-agreements --accept-package-agreements --silent" -Wait -NoNewWindow;$n=NodePath;if(-not$n){throw "Node.js tapılmadı."};Set-Content (Join-Path $root "installer\.node-installed-by-agent") "1" -Encoding ASCII;return$n}
function StopAppProcesses {$all=Get-CimInstance Win32_Process -ErrorAction SilentlyContinue;$t=@{};foreach($p in $all){if($p.ProcessId-ne$PID -and $p.CommandLine -and($p.CommandLine-like"*youtube_ai_agent*" -or$p.CommandLine-like"*$root*")){$t[$p.ProcessId]=$true}};foreach($p in $all|Where-Object{$t.ContainsKey($_.ProcessId)}){try{Stop-Process $p.ProcessId -Force -ErrorAction Stop}catch{}};Start-Sleep 2}
function Prep {foreach($d in @("config","logs","data","data/production","data/assets","data/videos","data/audio","data/scripts","data/captions","temp/processing","uploads/thumbnails")){New-Item -ItemType Directory -Force (Join-Path $root$d)|Out-Null};$e=Join-Path $root".env";if(!(Test-Path$e)){@("NODE_ENV=production","PORT=3456","LOG_LEVEL=info","DEFAULT_PRIVACY_STATUS=private","ENABLE_ANALYTICS=true","ANALYTICS_DB_PATH=./data/analytics.db","UPLOAD_PATH=./uploads","MAX_CONCURRENT_JOBS=1")|Set-Content$e-Encoding UTF8}}
function Creds {$p=Join-Path$root"config\credentials.json";$c=[ordered]@{};if(Test-Path $p){try{$o=Get-Content $p -Raw|ConvertFrom-Json;foreach($x in$o.PSObject.Properties){$c[$x.Name]=$x.Value}}catch{}};return$c}
function SaveCreds($c) {$c|ConvertTo-Json -Depth 20|Set-Content (Join-Path $root "config\credentials.json") -Encoding UTF8}
function Env($k,$v) {$p=Join-Path $root ".env";$a=if(Test-Path $p){Get-Content $p}else{@()};$a=@($a|Where-Object{$_-notmatch"^$([regex]::Escape($k))="});$a+=("$k=$v");$a|Set-Content $p -Encoding UTF8}
function VideoDb($node,$id) {$tmp=Join-Path$root"installer\.video.js";Set-Content $tmp "const{Database}=require('./database/db');(async()=>{const d=new Database();await d.initialize();await d.setSetting('video_provider',process.argv[1]);await d.close()})().catch(e=>{console.error(e);process.exit(1)})" -Encoding ASCII; & $node $tmp $id|Out-Null;$ok=$LASTEXITCODE;Remove-Item $tmp -Force; if($ok-ne0){throw"Video provider saxlanmadı."}}
function OAuth($node) {$h=Join-Path$root"installer\youtube-auth.js";$p = Start-Process $node -ArgumentList('"' + $h + '"')-WorkingDirectory $root-PassThru;$p.WaitForExit();if($p.ExitCode-ne0){throw"YouTube OAuth tamamlanmadı."}}
function Shortcut {$d=[Environment]::GetFolderPath("Desktop");$s=New-Object -ComObject WScript.Shell;$l=$s.CreateShortcut((Join-Path $d"$app.lnk"));$l.TargetPath="$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe";$l.Arguments="-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "+[char]34+$root+"\installer\launcher.ps1"+[char]34;$l.WorkingDirectory=$root;$l.Save()}

$f=New-Object System.Windows.Forms.Form;$f.Text="$app - Guided Setup";$f.Size=New-Object System.Drawing.Size(760,690);$f.StartPosition="CenterScreen";$f.FormBorderStyle="Sizable";$f.MaximizeBox=$true
$l=New-Object System.Windows.Forms.Label;$l.Text="$app — Walkthrough GUI";$l.Font=New-Object System.Drawing.Font("Segoe UI",20,[System.Drawing.FontStyle]::Bold);$l.Location=New-Object System.Drawing.Point(25,20);$l.AutoSize=$true;$f.Controls.Add($l)
$tabs=New-Object System.Windows.Forms.TabControl;$tabs.Location=New-Object System.Drawing.Point(20,65);$tabs.Size=New-Object System.Drawing.Size(705,500);$f.Controls.Add($tabs)
function Tab($n){$p=New-Object System.Windows.Forms.TabPage;$p.Text=$n;$tabs.TabPages.Add($p)|Out-Null;$p}
function Lab($p,$s,$y){$x=New-Object System.Windows.Forms.Label;$x.Text=$s;$x.Location=New-Object System.Drawing.Point(25,$y);$x.AutoSize=$true;$p.Controls.Add($x)}
function Box($p,$y,$pw=$false){$x=New-Object System.Windows.Forms.TextBox;$x.Location=New-Object System.Drawing.Point(25,$y);$x.Size=New-Object System.Drawing.Size(600,25);if($pw){$x.UseSystemPasswordChar=$true};$p.Controls.Add($x);$x}
function Sel($p,$items,$y){$x=New-Object System.Windows.Forms.ComboBox;$x.DropDownStyle="DropDownList";$x.Items.AddRange($items);$x.Location=New-Object System.Drawing.Point(25,$y);$x.Size=New-Object System.Drawing.Size(600,25);$p.Controls.Add($x);$x}
$a=Tab "1 AI";$v=Tab "2 Video";$y=Tab "3 YouTube";$c=Tab "4 Kanal";$r=Tab "5 Yekun"
Lab $a "AI provider"25;$ap=Sel $a @("Google Gemini","OpenAI","OpenRouter","Kimi (Moonshot AI)","MiMo (Xiaomi)","GLM (Zhipu AI)")50;$ap.SelectedIndex=0
Lab $a "API key (boş qala bilər)"90;$ak=Box $a115$true
Lab $a "Model"155;$am=Sel $a @("gemini-3.7-flash","gemini-3.1-pro-preview","gemini-3.5-flash-lite","gpt-5.6","gpt-5.6-terra","gpt-5.6-luna","openai/gpt-5.6-sol","google/gemini-3.7-flash","moonshotai/kimi-k3","z-ai/glm-5.3","kimi-k3","kimi-k2.7-code","mimo-v2.5-pro","mimo-v2.5","glm-5.3","glm-5.2","glm-5.1")180;$am.SelectedIndex=0
Lab $v "Video generation provider"25;$vp=Sel $v @("Local slideshow — no external video charges","ByteDance Seedance 2.5","MiniMax H3","Google Gemini Omni Flash","Kuaishou Kling 3.0 Omni","Alibaba Wan 2.7")50;$vp.SelectedIndex=0
Lab $v "API key / token (local slideshow üçün boş)"90;$vk=Box $v115$true;Lab $v "Secret key (Kling)"155;$vs=Box $v180$true
Lab $y "YouTube Client ID"25;$yc=Box $y50;Lab $y "YouTube Client Secret"90;$ys=Box $y115$true
$yo=New-Object System.Windows.Forms.CheckBox;$yo.Text="Client məlumatları saxlanandan sonra OAuth-u başlat";$yo.Location=New-Object System.Drawing.Point(25,160);$yo.AutoSize=$true;$yo.Checked=$true;$y.Controls.Add($yo)
$cb=New-Object System.Windows.Forms.Button;$cb.Text="Google Cloud Console";$cb.Location=New-Object System.Drawing.Point(25,195);$cb.Size=New-Object System.Drawing.Size(180,30);$y.Controls.Add($cb);$cb.Add_Click({Start-Process "https://console.cloud.google.com/"})
Lab $c "Channel name"25;$cn=Box $c50;Lab $c "Posting frequency"90;$cf=Sel $c @("Daily","Every other day","3 times per week","Weekly")115;$cf.SelectedIndex=0
Lab $c "Target audience"155;$ca=Box $c180;Lab $c "Default privacy"220;$cp=Sel $c @("private","unlisted","public")245;$cp.SelectedIndex=0
Lab $c "Preferred post time"285;$ct=Box $c310 180;$ct.Text="14:00";Lab $c "Channel description"350;$cd=Box $c375;$cd.Text="Automated content channel"
$rt=New-Object System.Windows.Forms.TextBox;$rt.Multiline=$true;$rt.ReadOnly=$true;$rt.ScrollBars="Vertical";$rt.Location=New-Object System.Drawing.Point(25,25);$rt.Size=New-Object System.Drawing.Size(620,390);$r.Controls.Add($rt)
$back=New-Object System.Windows.Forms.Button;$back.Text="Geri";$back.Location=New-Object System.Drawing.Point(420,585);$f.Controls.Add($back)
$next=New-Object System.Windows.Forms.Button;$next.Text="Növbəti";$next.Location=New-Object System.Drawing.Point(505,585);$f.Controls.Add($next)
$go=New-Object System.Windows.Forms.Button;$go.Text="Quraşdır";$go.Location=New-Object System.Drawing.Point(590,585);$f.Controls.Add($go)
$back.Add_Click({if($tabs.SelectedIndex-gt0){$tabs.SelectedIndex--}});$next.Add_Click({if($tabs.SelectedIndex-lt4){$tabs.SelectedIndex++}})
$tabs.Add_SelectedIndexChanged({if($tabs.SelectedIndex-eq4){$rt.Text="AI: "+$ap.SelectedItem+" / "+$am.SelectedItem+[Environment]::NewLine+"Video: "+$vp.SelectedItem+[Environment]::NewLine+"YouTube: "+$(if($yc.Text.Trim()){"Client ID daxil edilib"}else{"skip"})+[Environment]::NewLine+"Kanal: "+$cn.Text+[Environment]::NewLine+"Posting: "+$cf.SelectedItem+[Environment]::NewLine+"Audience: "+$ca.Text+[Environment]::NewLine+"Privacy: "+$cp.SelectedItem+[Environment]::NewLine+"Post time: "+$ct.Text}})
$go.Add_Click({$go.Enabled=$false;try{$n=EnsureNode;$env:Path=(Split-Path$n-Parent)+";"+$env:Path;$npm=Get-Command npm.cmd -ErrorAction SilentlyContinue;if(!$npm){throw"npm tapılmadı."};StopAppProcesses;Prep;$p = Start-Process $npm.Source -ArgumentList"ci --no-audit --no-fund"-WorkingDirectory $root-Wait-PassThru-WindowStyle Hidden;if($p.ExitCode-ne0){throw"npm ci uğursuz oldu."};$q=Creds;$map=@{"Google Gemini"="gemini";"OpenAI"="openai";"OpenRouter"="openrouter";"Kimi (Moonshot AI)"="kimi";"MiMo (Xiaomi)"="mimo";"GLM (Zhipu AI)"="glm"};$id=$map[$ap.SelectedItem];if($ak.Text.Trim()){if($id-eq"gemini"){$q.gemini=[ordered]@{apiKey=$ak.Text.Trim();model=$am.SelectedItem}}else{$q.aiProvider=[ordered]@{provider=$id;apiKey=$ak.Text.Trim();model=$am.SelectedItem}}};$vm=@{"Local slideshow — no external video charges"="slideshow";"ByteDance Seedance 2.5"="seedance";"MiniMax H3"="minimax_h3";"Google Gemini Omni Flash"="google_omni";"Kuaishou Kling 3.0 Omni"="kling";"Alibaba Wan 2.7"="wan"};$vid=$vm[$vp.SelectedItem];if($vk.Text.Trim()){switch($vid){"seedance"{$q.replicate=[ordered]@{apiKey=$vk.Text.Trim()}};"minimax_h3"{$q.minimax=[ordered]@{apiKey=$vk.Text.Trim()}};"google_omni"{$q.gemini=[ordered]@{apiKey=$vk.Text.Trim()}};"kling"{$q.kling=[ordered]@{accessKey=$vk.Text.Trim();secretKey=$vs.Text.Trim()}};"wan"{$q.wan=[ordered]@{apiKey=$vk.Text.Trim()}}}};if($yc.Text.Trim()){$q.youtube=[ordered]@{client_id=$yc.Text.Trim();client_secret=$ys.Text.Trim();redirect_uris=@("http://127.0.0.1")}};$q.channel=[ordered]@{channelName=$cn.Text.Trim();channelDescription=$cd.Text.Trim();defaultCategory="22";defaultPrivacy=$cp.SelectedItem};$fm=@{"Daily"="daily";"Every other day"="every-2-days";"3 times per week"="3-per-week";"Weekly"="weekly"};$q.content=[ordered]@{contentTypes=@("tutorial","explainer","list");competitorChannels=@();targetAudience=$ca.Text.Trim();postingFrequency=$fm[$cf.SelectedItem];preferredPostTime=$ct.Text.Trim()};SaveCreds $q;Env"CHANNEL_NAME"$cn.Text.Trim();Env"DEFAULT_AUTHOR"$cn.Text.Trim();Env"TARGET_AUDIENCE"$ca.Text.Trim();Env"DEFAULT_PRIVACY_STATUS"$cp.SelectedItem;VideoDb $n $vid;if($yc.Text.Trim() -and $yo.Checked){OAuth $n};Shortcut;[System.Windows.Forms.MessageBox]::Show("Walkthrough konfiqurasiyası saxlanıldı. Desktop shortcut yaradıldı.",$app,"OK","Information")|Out-Null;$f.Close()}catch{[System.Windows.Forms.MessageBox]::Show($_.Exception.Message,"Quraşdırma xətası","OK","Error")|Out-Null;$go.Enabled=$true}})
[void]$f.ShowDialog()
